language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO="django==1.5 --use-mirrors"
  - DJANGO="django==1.4 --use-mirrors"
  - DJANGO="django==1.3.1 --use-mirrors"
  - DJANGO="django==1.6 --use-mirrors"

install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

script:
  - coverage run --source=ydcommon setup.py test

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.3.1 --use-mirrors"

after_success:
  - coverage report --omit="ydcommon/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
